updated T&C page layout
near-horizon/horizon pull request #36
Opened 2023-07-10 14:11 UTC by humanman

tweaked style so page is a little easier to read

2023-07-11 07:51 UTC, petarvujovic98 requested changes

2023-07-11 07:51 UTC, petarvujovic98 commented on widgets/src/TNCPage.jsx
> +  <Container ass="c12 c20 doc-content">
There is a typo here. It should be `class` not `ass`.

2023-07-11 14:58 UTC, humanman commented
@petarvujovic98 fixed

2023-07-12 10:22 UTC, petarvujovic98 approved these changes

2023-07-12 10:22 UTC, merged