Created activity and reward credit tabs, pages, tables. Rendering ske…
near-horizon/horizon pull request #61
Opened 2023-10-20 13:25 UTC by CDAracena

…leton for credits banner and layout children, fixed incentives api call typo.

2023-10-20 13:47 UTC, CDAracena commented
@petarvujovic98 I wanted to discuss redirects between the `/credits`  parent route and the nested `/credits/activity` route before this PR gets merged, since I wanted to confirm if `/credits/activity` should be the default when someone attempts to navigate to `/credits` and how to go about that if that's the case

2023-10-20 18:12 UTC, petarvujovic98 commented
You are correct, you can see how I did a similar redirect in the [project page] (https://github.com/near-horizon/horizon/blob/website/app/src/app/projects/[accountId]/page.tsx#L5-L11)

2023-10-23 09:16 UTC, petarvujovic98 requested changes

2023-10-23 09:16 UTC, petarvujovic98 commented on app/src/app/account/credits/available-credits-banner.tsx
> +  );
I would use an existing function to fetch the project here. I would also redirect to the login route if there is no user like seen in the dashboard page.

2023-10-23 12:46 UTC, petarvujovic98 requested changes

2023-10-23 12:46 UTC, petarvujovic98 commented on app/src/app/account/credits/available-credits-banner.tsx
> +  const horizonProject = await getProject(user?.accountId);
You don't need to use optional chaining here since it is known that the user exists, otherwise the function would exit early 3 lines above.

2023-10-24 12:49 UTC, merged